### PR TITLE
Setting up segment tracking [stage-2]

### PR DESCRIPTION
**Pull request by alex-deaconu**
Updating ch version

Added tracker service & tracking functions

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@olegrise @rodrigopavezi please review. Thanks.

**Comment by olegrise** [comment]
:+1:

**Comment by alex-deaconu** [comment]
@rodrigopavezi added an additional check for the eventName; let me know if you feel this is sufficient. Thanks.

**Comment by rodrigopavezi** [comment]
LG :+1:

**Pull request merged**
