### PR TITLE
[feature] Manage display page

### PR DESCRIPTION
**Pull request by alex-deaconu**
Updated routing
Fixed button styling
Time picker directive, resolution filter and delete modal

@EnlightenedCode Manage Display is not quite finished but adding/loading a display works. Please review. Thanks.

### CODE REVIEW

**Comment by EnlightenedCode** [comment]
@alex-deaconu are the buttons hooked up on add Display? when I run locally they do nothing although I see the code there.  small things I noticed.  there are some jslint errors. make a quick commit to fix those up.  Add Display button doesn't go away when you go into the add display screen.

**Comment by alex-deaconu** [comment]
@EnlightenedCode no, I haven't created services for add/update/restart/reset yet. Working on that now. I'm not sure about lint errors, I fixed those for this commit. What exactly are you seeing?
The Add button is supposed to stay up on the Display screen it's like that in the mockups.
Thanks.

**Comment by EnlightenedCode** [comment]
@alex-deaconu when I run npm run build it comes up with jslint errors.  :+1:  looks good then.

**Comment by alex-deaconu** [comment]
@EnlightenedCode weird. I made a point to fix the lint errors for this commit. Merging then. Thanks.

**Pull request merged**
