### PR TITLE
[chore] Cleaned up index.html scripts

### PR DESCRIPTION
**Pull request by alex-deaconu**
Removed libraries are available through dependencies.js from CH

@rodrigopavezi please review. Thanks!

### CODE REVIEW

**Comment by alex-deaconu** [comment]
Build is now fixed. @rodrigopavezi FYI.

**Comment by rodrigopavezi** [comment]
@alex-deaconu I wonder. Should we really use the dependencies.js? I haven't had good experience with it on the apps I worked on. I changed them to load each library separated. Also If I am not wrong it slow down the loading of the app as it has to wait for this huge file to be downloaded and loaded. We cannot use the HTML5's new 'async' attribute. Thoughts? cheers

**Comment by alex-deaconu** [comment]
@rodrigopavezi the idea here is to prevent this warning: http://screencast.com/t/CcApiRevNb. We're loading angular, jquery, ui-bootstrap twice each time we run the app.

With regards to loading time, we build all JS files into 1 displays.min.js which is currently about 800kb, served as gzip and cached for subsequent requests. We can optimize later if we find this file becomes too large. This approach relies on a single large file, vs multiple files, to reduce the number of individual requests needed to load all scripts.

@olegrise thoughts? Thanks.

**Comment by olegrise** [comment]
@alex-deaconu @rodrigopavezi for me it's not white and black. I believe on mobile website loads faster if it makes less requests, so it's good to have everything in one file. Also I believe putting everything in one file eliminates unnecessary complexity of making sure dependencies are loaded before you can start using them. However I also see a benefit in loading popular libraries such as JQuery and AngularJS from their own CDN. I think either way is fine.

The separate question however is why you are seeing the warning "Tried to load angular more than once". I wonder if compiling all dependencies in one one file actually solves this problem or just hides it.

**Comment by alex-deaconu** [comment]
@olegrise in this particular case, dependencies.js contains Angular, and we also load `//ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.js`. Since both files load Angular, we're getting that warning. FYI @rodrigopavezi. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu I was questioning about the asynchronous due to the analysis googles does to the site:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdisplays.risevision.com%2F

They are saying we have a render blocking.

Thoughts?
@olegrise FYI.

**Comment by olegrise** [comment]
@alex-deaconu okay re. "dependencies.js contains Angular". Makes sense.

**Comment by alex-deaconu** [comment]
@rodrigopavezi okay. To be honest, I don't know what can be done to resolve this with Angular. We don't show anything until it (Angular) loads, because we don't have any HTML content to show. Unless we fix this issue at its root, I think render blocking is something we have to live with. And from my reading it has nothing to do with async script loading. 

Here's a quick discussion I found on this subject: https://groups.google.com/forum/#!topic/angular/id_UBdtzFew. It's just a matter of showing some HTML content on your page, rather than leaving it blank.

Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu I guess to fix that with angular we would have to implement something like that

_What if I'm using a JavaScript framework to construct the page?
If the content of the page is constructed by client-side JavaScript, then you should investigate inlining the relevant JavaScript modules to avoid extra network roundtrips. Similarly, leveraging server-side rendering can significantly improve first page load performance: render JavaScript templates on the server to deliver fast first render, and then use client-side templating once the page is loaded. For more information on server-side rendering, see http://youtu.be/VKTWdaupft0?t=14m28s._

https://developers.google.com/speed/docs/insights/BlockingJS

I would do it now unless we find out that our customers are not happy with the performance of our apps.

cheers

**Comment by rodrigopavezi** [comment]
LG :+1:

**Comment by olegrise** [comment]
:+1:

**Pull request merged**
