### PR TITLE
[fix] playerStatus renamed to playerErrorCode

### PR DESCRIPTION
**Pull request by alex-deaconu**
Added orientation to API fields
Fixed issue with select element ng-model
Updated CH and common-style versions

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@olegrise please review. Thanks!

**Comment by olegrise** [comment]
:+1:

**Comment by alex-deaconu** [comment]
@olegrise, another fix for display add I'd like to get in with this PR. See second commit. Thanks.

**Comment by olegrise** [comment]
Look good.

**Comment by alex-deaconu** [comment]
Thanks @olegrise!

**Pull request merged**
