### PR TITLE
[feature] Added a simple search filter

### PR DESCRIPTION
**Pull request by alex-deaconu**
Refactored display service to be more angularized
Added tests for service
Added displays filter with tagging UI features
Only text box search works at this point

Also includes jsbeautify results.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@EnlightenedCode please review. Thanks.

**Comment by EnlightenedCode** [comment]
:+1:  looks good. question...  I noticed the search works where you type and then press enter? is this expected? I know in storage-client we have it to where the filter results update on every keyup...rather then waiting for enter... Just wanted to see if we are going to be consistent with that one way or the other.

**Comment by alex-deaconu** [comment]
@EnlightenedCode good question. For now the search behaviour is based on the Common Header's Company list, which works in that manner. The problem is that search contacts the API (while Storage filters locally) which means that results are not real time. A good alternative is similar to how select2 does it, with a delay of a couple of seconds after the user stops typing, to ensure they're "done". Something to think about for all apps as a whole. Thanks!

**Comment by ByronDarlison** [comment]
@alex-deaconu @EnlightenedCode I think we need to standardize on how search works and how lists are presented and we need to have the same pattern applied everywhere. This is an extremely common and often used feature so it has to be consistent and work well.

What I believe our standard is, and if it isn't, it should be, is as follows:

- start typing, stop (delay 1 second), search results returned from service and displayed, only the first 100 records or so, to make it fast, there are situations where there are thousands upon thousands of records and we have found that these queries will timeout, only retrieve what the user can see
- user scrolls down through the list when they hit the 75th record or so, the query fires again and retrieves the next batch
- user changes the sort order of a column, query fires and returns the first 100 records or so
- search field has an X on the right, user clicks it, clears the search terms and list returns first 100 records or so

For greater certainty. Search only retrieves enough records to show the user a page worth of returned values. If they scroll down, query get's next batch, and so on, infinite scroll style. User changes search criteria, or sort, pattern fires and repeats. When typing in a search box if the user pauses that is the criteria for the search and the search query fires. They don't have to click a search button. Search boxes always have delete X's on the right so that the user doesn't have to backspace through their whole query to get rid of it.

@alex-deaconu @EnlightenedCode @tejohnso @fjvallarino @ghislaineguerin @olegrise @stevesherrie @alanclayton @brianloosbrock @rodrigopavezi @alexey-rise @donnapep @stulees can you review and confirm you are in agreement with the requirement and from this point forward can we implement all search and lists according to this, assuming we all concur. And if we do, @alanclayton can you make sure that this criteria is applied by QA everywhere.

Thanks!

**Comment by donnapep** [comment]
@ByronDarlison Makes sense. Only thing I would add is that when the user scrolls to the bottom of the results it may be helpful to give some sort of indicator that more results are loading.

**Comment by alexey-rise** [comment]
@ByronDarlison makes sense to me. Thanks

**Comment by olegrise** [comment]
Makes sense. Sounds like we need a common Search Bar component.

**Comment by stulees** [comment]
@ByronDarlison Agree on all points and also with Oleg that a common component would be ideal, thanks

**Comment by ByronDarlison** [comment]
@donnapep makes sense re. loading indicator. I missed that. @alex-deaconu @EnlightenedCode @tejohnso @fjvallarino @ghislaineguerin @stevesherrie @alanclayton @brianloosbrock @rodrigopavezi @alexey-rise what do you think?

**Comment by tejohnso** [comment]
This is for a drop down type-ahead search?
If this is also for table lists I would add that the fetch result size should be configurable.

**Comment by ByronDarlison** [comment]
@tejohnso not sure what you mean by drop down type-ahead search?

**Comment by tejohnso** [comment]
Actually I don't think it matters if it's a drop down search or not.  Regardless of the use case I think the fetch size results should be configurable.  For some queries we'll want to return 100 results, but for others maybe 10, and others maybe 500.  It should be easy for the user of this component to change the result size.

**Comment by alex-deaconu** [comment]
@ByronDarlison agreed. Added this as a task on the Apps board: https://trello.com/c/1bzRXmpA/233-standard-search-bar-component. Thanks.

**Comment by alanclayton** [comment]
@ByronDarlison Makes sense. In addition to what @donnapep says re: showing the loading spinner, if for whatever reason the end of the list has been reached, tell that to the User.  Once @alex-deaconu finishes the component we will incorporate this as part of our QA process.

**Comment by ByronDarlison** [comment]
@alanclayton agreed. @alex-deaconu thanks for adding.

**Pull request merged**
