### PR TITLE
Fixed add displays test to delete the added display.

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@alex-deaconu please review. I will move the common e2e scripts to a node module when I get a chance. cheers

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@rodrigopavezi nice :+1: . I'm wondering if you can also Schedules? Thanks.

**Comment by alex-deaconu** [comment]
Oops, looks like tests are failing for this. Any ideas?

**Comment by rodrigopavezi** [comment]
@alex-deaconu It was fixed now. Guess what was causing it to fail. It is was the resolution of the browser window. With a lower resolution the delete button is not on the screen to be clicked.

**Comment by alex-deaconu** [comment]
@rodrigopavezi oh wow. That's weird. Does that mean that if we have a taller page we would have to scroll to the bottom to get to it?

**Comment by rodrigopavezi** [comment]
@alex-deaconu I think so. They mentioning to use browser.actions().mouseMove(element).click(); I haven't tried though. cheers

**Pull request merged**
