### PR TITLE
[feature] ux updates

### PR DESCRIPTION
**Pull request by ghislaineguerin**
@alex-deaconu I'm pushing the list and scroll bar visibility fix. We also need to use the same solution we had for selectors. You will see I've added a script a the bottom for showing how it should work.

1dtck6b0xm

```
<script type="text/javascript">
    $(window).resize(function() {
    $('.auto-height').height($(window).height() -  $('.app-header').height() -  $('.navbar').height() - $('.app-footer').height() - 140);
    });
    $(window).trigger('resize');
</script>

```

### CODE REVIEW

**Comment by ghislaineguerin** [comment]
@alex-deaconu make sure to bower update the latest branch,

**Comment by alex-deaconu** [comment]
@ghislaineguerin couple of things:
- Looks like the status colours are no longer showing correctly. Can you take a look?
- Re: auto-resize of the list, I will add that handler to the scrolling-list component; added https://github.com/Rise-Vision/common-app-components/issues/10 for this; will remove the script once that's implemented
- To mock this or any PR, you can use [stage-0] in the commit message (or 1, 2), it will be mocked at the corresponding displays-stage-0.risevision.com url
Otherwise looks good. Thanks for the cleanup! :+1:

**Comment by ghislaineguerin** [comment]
@alex-deaconu I was to move the colors to utilities.scss and then I lost them! sorry will fix.

**Comment by ghislaineguerin** [comment]
@alex-deaconu I've added back the status colors to the common-styles branch. And fixed an issue where the add displays input group had a margin because of the status not showing there. Also moved an icon to the correct side.

**Comment by ghislaineguerin** [comment]
@alex-deaconu ignore last post. I forgot to update bower.

**Comment by alex-deaconu** [comment]
@ghislaineguerin I need to rebase this PR, can I squash all the commits? Thanks.

**Comment by ghislaineguerin** [comment]
@alex-deaconu sure, please do that. Thanks!

**Comment by alex-deaconu** [comment]
@ghislaineguerin I think this PR is ready for merge. However, before that we should merge the corresponding common-style branch and create a new version tag. Is that something you can take care of? Thanks!

**Comment by ghislaineguerin** [comment]
@alex-deaconu sure. I'll take care of it.

**Comment by alex-deaconu** [comment]
Awesome, thanks @ghislaineguerin!

**Comment by alex-deaconu** [comment]
Corresponding PR in common-style is pending review (https://github.com/Rise-Vision/common-style/pull/132). Will update bower version w/ new tag when available.

@rodrigopavezi please review. Thanks.

**Comment by rodrigopavezi** [comment]
LG :+1:

**Pull request merged**
