### PR TITLE
[feature] Integrated ui.router

### PR DESCRIPTION
**Pull request by alex-deaconu**
Using .go and ui-sref for navigation
Integrated risevision.company.selectedCompanyChanged event`
Updated tests
Removed extra bower dependencies imported by CH

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@tejohnso please review. @olegrise @rodrigopavezi FYI. Thanks.

**Comment by tejohnso** [comment]
Nice. Is there any reason that the ui router version can't be bumped up?

**Comment by alex-deaconu** [comment]
@tejohnso good point. Missed that, bumped version and used `~`. Thanks!

**Comment by alex-deaconu** [comment]
This is now ready for merge. Added a couple of other changes in 2 more commits.

@rodrigopavezi please review. Thanks.

**Comment by alex-deaconu** [comment]
@rodrigopavezi as per your suggestion, I've split out the authentication code from app.js into a service, w/ tests.

Please review. Thanks.

**Comment by rodrigopavezi** [comment]
@alex-deaconu awesome BIG LG! :+1: thanks for changing.

**Comment by alex-deaconu** [comment]
Thanks for bringing it up; great simplification!

**Pull request merged**
