### PR TITLE
Check Display Administrator role

### PR DESCRIPTION
**Pull request by alex-deaconu**
Use require-role directive to remove actions if not allowed

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc please review. Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu I think we should hide the Add Display button as well. Cheers

**Comment by alex-deaconu** [comment]
@ezequielc updated to remove Add Display buttons from the List and Manage pages. Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Thanks! :+1:

**Pull request merged**
